const initialState = {
  comments: [
    {
      id: 1,
      text:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      profilePic:
        'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      name: 'Jan Kowalski',
      client: 'Feuture client',
    },
    {
      id: 2,
      text:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      profilePic:
        'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      name: 'Anna Kowalska',
      client: 'Feuture client',
    },
    {
      id: 3,
      text:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      profilePic:
        'https://images.pexels.com/photos/697509/pexels-photo-697509.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      name: 'Jhon Smith',
      client: 'Feuture client',
    },
  ],
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      oldPrice: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: true,
      compare: false,
      photoBackground:
        'https://s1.meble.pl/gfx/_zdjecia_wspolne/sklep_oferta/2/743/2743454/bzielona_kanapa_w_skandynawskim_stylu_pik___index__4176921222.jpg',
      myRating: 3,
      isFavourite: true,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      oldPrice: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: true,
      compare: false,
      photoBackground:
        'https://lectus24.pl/96216-large_default/biurko-z-szufladami-raflo-biale-mat.jpg',
      myRating: null,
      isFavourite: false,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      oldPrice: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      compare: false,
      photoBackground:
        'https://www.meblezagrosze.pl/upload/l650/szafka-rtv-sewt142-m115-colonial-oak-black-colonial-oak-sewill-1.jpg',
      isFavourite: false,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground: 'https://www.mirjan24.pl/83016/komoda-nowoczesna-empire.jpg',
      isFavourite: false,
      compare: false,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://meblini.pl/userdata/public/gfx/23421/Stolik-kawowy-lawa-2w1-okragly-industrialny-w-stylu-loft-Dab-Craft-Zloty.jpg',
      isFavourite: false,
      compare: false,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.strefasypialni.pl/userdata/public/gfx/5848/Lozko-Texas_90.jpg',
      isFavourite: false,
      compare: false,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.seart.pl/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/w/i/witryna-industrial-2-seart-5.jpg',
      isFavourite: false,
      compare: false,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground: 'https://birdmeble.pl/userdata/public/gfx/4474.jpg',
      isFavourite: false,
      compare: false,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://a.allegroimg.com/original/038030/4e128be0469db48ff02ea169cb2a/PIKO-LAWA-STOLIK-KAWOWY-LOFT-RETRO-INDUSTRIALNY',
      isFavourite: false,
      compare: false,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://meblowy.salon/userdata/public/gfx/3152/Rozkladana-sofa-Corner-z-podnozkiem-niebieska.jpg',
      isFavourite: false,
      compare: false,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://3.allegroimg.com/s1024/0c7717/0cb014b14a218bcae20a9cad26d3',
      isFavourite: false,
      compare: false,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea-club.org/cache/zoo_images/d/d8b2d6766a1f0a7c43be4cb92958dd32.jpg',
      isFavourite: false,
      compare: false,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://umeblowana.com/userdata/public/gfx/5379/Komplet-mebli-do-lazienki-w-stylu-loft-80-cm.jpg',
      isFavourite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.lustrodlaciebie.pl/galerie/l/lustro-do-makijazu-wizazu-holl_2032.jpg',
      isFavourite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://bromarkt.pl/pol_pl_Duza-szafa-na-ubrania-180-cm-Dab-artisan-czarny-ISMENA-932_3.jpg',
      isFavourite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://a.allegroimg.com/original/11fe09/a41ca80f44a1b06d0467ed8d7458/Szafa-na-Ubrania-Garderoba-Skladana-XXL-Tekstylna',
      isFavourite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.resmar.pl/pol_pl_Zestaw-mebli-kuchennych-290x215-cm-Modena-24536_1.jpg',
      isFavourite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://antyki24.pl/environment/cache/images/500_500_productGfx_e1be05b730a946274d13299ecc6230bc.jpg',
      isFavourite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://i.dobrzemieszkaj.pl/i/72/13/41/r3/1920/meble-do-salonu-10-swietnych-kolekcji-na-kazda-kieszen.jpg',
      isFavourite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://mebletwojemiejsce.pl/fotosD/13_meble_z_litego_drewna_na_wymiar_warszawa.jpg',
      isFavourite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://meblini.pl/userdata/public/gfx/20450/krzeslo-TUGO-2-do-jadalni-kuchni.jpg',
      isFavourite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.zyrandole24.pl/images/allegro_foto/zdjecia/K213/IMG_2244-30-01-19-01-10.jpeg',
      isFavourite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground: 'https://lissy.pl/wp-content/uploads/Witryna-150-Lugo.jpg',
      isFavourite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://lissy.pl/wp-content/uploads/szafka-nocna-Lugo-aranz.jpg',
      isFavourite: true,
      compare: false,
    },
    {
      id: 'henriksdal-1',
      name: 'Henriksdal 1',
      category: 'chair',
      price: 30,
      oldPrice: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      like: true,
      compare: false,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/ingolf-stolek-barowy-z-oparciem-bialy__0873775_pe595558_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-2',
      name: 'Henriksdal 2',
      category: 'chair',
      price: 30,
      oldPrice: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/dalfred-stolek-barowy-czarny__0874458_pe595557_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-3',
      name: 'Henriksdal 3',
      category: 'chair',
      price: 30,
      oldPrice: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/stig-stolek-barowy-z-oparciem-czarny-czarny__0948113_pe798868_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-4',
      name: 'Henriksdal 4',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/henriksdal-stolek-barowy-z-oparciem-ciemnobrazowy-vibberbo-czarny-bezowy__0770696_pe755597_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-5',
      name: 'Henriksdal 5',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/franklin-taboret-skladany-z-oparciem-czarny-czarny__0874580_pe680502_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-6',
      name: 'Henriksdal 6',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/nordviken-stolek-barowy-z-oparciem-czarny__0797137_pe766703_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-7',
      name: 'Henriksdal 7',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/henriksdal-pokrycie-stolka-barowego-z-oparciem-vibberbo-czarny-bezowy__0770696_pe755597_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-8',
      name: 'Henriksdal 8',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/henriksdal-stolek-barowy-z-oparciem-rama-ciemnobrazowy__0873493_pe590683_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-9',
      name: 'Henriksdal 9',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/nilsolle-stolek-barowy-brzoza__0874053_pe595533_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-10',
      name: 'Henriksdal 10',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/franklin-taboret-skladany-z-oparciem-bialy-bialy__0874577_pe680524_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-11',
      name: 'Henriksdal 11',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/raskog-stolek-barowy-czarny__0873897_pe620307_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-12',
      name: 'Henriksdal 12',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/norraryd-stolek-barowy-z-oparciem-czarny__0873586_pe689186_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-13',
      name: 'Henriksdal 13',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/janinge-stolek-barowy-szary__0873831_pe595574_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-14',
      name: 'Henriksdal 14',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/glenn-stolek-barowy-bialy-chrom__0873987_pe653485_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-15',
      name: 'Henriksdal 15',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/franklin-taboret-skladany-z-oparciem-bialy-bialy__0873922_pe680516_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-16',
      name: 'Henriksdal 16',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/yngvar-stolek-barowy-antracyt__0929674_ph170546_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-17',
      name: 'Henriksdal 17',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/henriksdal-stolek-barowy-z-oparciem-brazowoczarny-glose-czarny__0873533_pe595540_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-18',
      name: 'Henriksdal 18',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/bernhard-stolek-barowy-z-oparciem-chrom-mjuk-bialy__0873458_pe595556_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-19',
      name: 'Henriksdal 19',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/bernhard-stolek-barowy-z-oparciem-chrom-mjuk-ciemnobrazowy__0743277_pe742950_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-20',
      name: 'Henriksdal 20',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/norraker-stolek-barowy-z-oparciem-brzoza__0873716_pe720507_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-21',
      name: 'Henriksdal 21',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/ekedalen-stolek-barowy-z-oparciem-ciemnobrazowy-orrsta-jasnoszary__0872149_pe720430_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-22',
      name: 'Henriksdal 22',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/volfgang-stolek-barowy-z-oparciem-chrom-gunnared-srednioszary__0873681_pe700225_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-23',
      name: 'Henriksdal 23',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/bekvaem-taboret-ze-schodkiem-brzoza__0870863_pe602961_s5.jpg?f=xxs',
    },
    {
      id: 'henriksdal-24',
      name: 'Henriksdal 24',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/lidkullen-stolek-do-siedzenia-stania-gunnared-ciemnoszary__0798458_pe767227_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-1',
      name: 'Evertsberg 1',
      category: 'sofa',
      price: 30,
      oldPrice: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      like: true,
      compare: false,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/angsta-rozkladana-sofa-3-osobowa-z-szezlongiem-szary__1011692_pe828535_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-2',
      name: 'Evertsberg 2',
      category: 'sofa',
      price: 30,
      oldPrice: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/glostad-sofa-2-osobowa-knisa-ciemnoszary__0950898_pe800738_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-3',
      name: 'Evertsberg 3',
      category: 'sofa',
      price: 30,
      oldPrice: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/friheten-naroznik-z-funkcja-spania-skiftebo-ciemnoszary__0833845_pe603738_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-4',
      name: 'Evertsberg 4',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/arviken-sofa-trzyosobowa-rozkladana-bezowy__0277586_pe416615_s5.jpg?f=xxss',
    },
    {
      id: 'Evertsberg-5',
      name: 'Evertsberg 5',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/ektorp-sofa-3-osobowa-remmarn-jasnoszary__0924993_pe788685_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-6',
      name: 'Evertsberg 6',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/asarum-rozkladana-sofa-3-osobowa-granatowy__1011233_pe828427_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-7',
      name: 'Evertsberg 7',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/soederhamn-sekcja-3-osobowa-samsta-ciemnoszary__0666104_pe713402_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-8',
      name: 'Evertsberg 8',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/bastubo-rozkladana-sofa-3-osobowa-z-szezlongiem-jasnoszary__0940238_pe794894_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-9',
      name: 'Evertsberg 9',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/evertsberg-sofa-2-osobowa-rozkladana-z-pojemnikiem-ciemnoszary__0799073_pe767472_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-10',
      name: 'Evertsberg 10',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/askeby-sofa-dwuosobowa-rozkladana-niebieski__0834858_pe645547_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-11',
      name: 'Evertsberg 11',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/ektorp-sofa-2-osobowa-remmarn-jasnoszary__0818542_pe774473_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-12',
      name: 'Evertsberg 12',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/graelviken-rozkladana-sofa-3-osobowa-ciemnoszary__0830273_pe720080_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-13',
      name: 'Evertsberg 13',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/holmsund-naroznik-z-funkcja-spania-nordvalla-srednioszary__0829250_pe600302_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-14',
      name: 'Evertsberg 14',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/nyhamn-rozkladana-sofa-3-osobowa-z-materacem-piankowym-knisa-szary-bez__0767327_pe754068_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-15',
      name: 'Evertsberg 15',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/askesta-rozkladana-sofa-3-osobowa-skiftebo-zolty__0779684_pe759648_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-16',
      name: 'Evertsberg 16',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/landskrona-sofa-2-osobowa-gunnared-ciemnoszary-drewno__0825406_pe680171_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-17',
      name: 'Evertsberg 17',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/bennebol-rozkladana-sofa-3-osobowa-z-szezlongiem-granatowy__0940191_pe794866_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-18',
      name: 'Evertsberg 18',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/knopparp-sofa-2-osobowa-knisa-jasnoszary__0827225_pe706767_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-19',
      name: 'Evertsberg 19',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/ektorp-sofa-narozna-4-osobowa-remmarn-jasnoszary__0818596_pe774525_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-20',
      name: 'Evertsberg 20',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/holmsund-sofa-trzyosobowa-rozkladana-nordvalla-srednioszary__0834611_pe600340_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-21',
      name: 'Evertsberg 21',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/kivik-sofa-trzyosobowa-orrsta-jasnoszary__0788749_pe763721_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-22',
      name: 'Evertsberg 22',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/soederhamn-sofa-3-osobowa-samsta-ciemnoszary__0666156_pe713429_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-23',
      name: 'Evertsberg 23',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/grimhult-rozkladana-sofa-3-osobowa-szary__0947880_pe798685_s5.jpg?f=xxs',
    },
    {
      id: 'Evertsberg-24',
      name: 'Evertsberg 24',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/soederhamn-sofa-4-osobowa-z-szezlongiem-i-otwarty-koniec-samsta-ciemnoszary__0666445_pe713552_s5.jpg?f=xxss',
    },
    {
      id: 'Melltorp-1',
      name: 'Melltorp 1',
      category: 'table',
      price: 30,
      oldPrice: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      like: true,
      compare: false,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/melltorp-stol-bialy__0870501_pe695865_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-2',
      name: 'Melltorp 2',
      category: 'table',
      price: 30,
      oldPrice: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/tarsele-stol-rozkladany-okl-deb-czarny__0944977_pe797515_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-3',
      name: 'Melltorp 3',
      category: 'table',
      price: 30,
      oldPrice: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/danderyd-stol-bialy__0946312_ph172540_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-4',
      name: 'Melltorp 4',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/ingatorp-stol-rozkladany-szary__0870671_pe691012_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-5',
      name: 'Melltorp 5',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/linnmon-adils-stol-bialy__0737165_pe740925_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-6',
      name: 'Melltorp 6',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/lack-stolik-bialy__0702208_pe724343_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-7',
      name: 'Melltorp 7',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/micke-biurko-bialy__0851508_pe565256_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-8',
      name: 'Melltorp 8',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/melltorp-stol-bialy__0870501_pe695865_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-9',
      name: 'Melltorp 9',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/malm-toaletka-bialy__0858727_pe555871_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-10',
      name: 'Melltorp 10',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/micke-biurko-bialy__0851288_pe565258_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-11',
      name: 'Melltorp 11',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/micke-biurko-bialy__0921905_pe787996_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-12',
      name: 'Melltorp 12',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/lack-stolik-kawowy-bialy__0702217_pe724349_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-13',
      name: 'Melltorp 13',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/vittsjoe-stolik-pod-laptopa-czarnobraz-szklo__0855294_pe564652_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-14',
      name: 'Melltorp 14',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/lagkapten-olov-biurko-dab-bejcowany-na-bialo-bialy__0977612_pe813682_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-15',
      name: 'Melltorp 15',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/lagkapten-adils-biurko-bialy__0977229_pe813472_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-16',
      name: 'Melltorp 16',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/malm-biurko-z-wysuwanym-panelem-bialy__0403679_pe565683_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-17',
      name: 'Melltorp 17',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/malm-biurko-bialy__0850916_pe602578_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-18',
      name: 'Melltorp 18',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/lagkapten-alex-biurko-bialy__0977483_pe813612_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-19',
      name: 'Melltorp 19',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/tarsele-stol-rozkladany-okl-deb-czarny__0944977_pe797515_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-20',
      name: 'Melltorp 20',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/hemnes-biurko-biala-bejca__0849790_pe616054_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-21',
      name: 'Melltorp 21',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/brimnes-biurko-bialy__0926236_pe789116_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-22',
      name: 'Melltorp 22',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/ingatorp-stol-rozkladany-bialy__0870419_pe668361_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-23',
      name: 'Melltorp 23',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/taerendoe-stol-czarny__0720893_ph004838_s5.jpg?f=xxs',
    },
    {
      id: 'Melltorp-24',
      name: 'Melltorp 24',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/bjursta-stol-rozkladany-okl-deb__0870090_pe594429_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-1',
      name: 'Tommaryd 1',
      category: 'dining',
      price: 30,
      oldPrice: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      like: true,
      compare: false,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/norraker-lawka-brzoza__0682550_pe720526_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-2',
      name: 'Tommaryd 2',
      category: 'dining',
      price: 30,
      oldPrice: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/tommaryd-stol-okleina-debowa-bejcowana-na-bialo-bialy__0939691_pe794636_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-3',
      name: 'Tommaryd 3',
      category: 'dining',
      price: 30,
      oldPrice: 45,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/norraker-norraryd-stol-barowy-i-2-stolki-czarny-czarny__0871732_pe696583_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-4',
      name: 'Tommaryd 4',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/norraker-stolek-brzoza__0682556_pe720528_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-5',
      name: 'Tommaryd 5',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/yngvar-krzeslo-antracyt__0750850_pe746841_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-6',
      name: 'Tommaryd 6',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/stensele-norraryd-stol-barowy-i-2-stolki-antracyt-antracyt-czarny__0872101_pe719776_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-7',
      name: 'Tommaryd 7',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/norraker-stol-brzoza__0682560_pe720534_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-8',
      name: 'Tommaryd 8',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/roenninge-krzeslo-zielony__0933468_ph168894_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-9',
      name: 'Tommaryd 9',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/norraryd-stolek-barowy-z-oparciem-czarny__0873586_pe689186_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-10',
      name: 'Tommaryd 10',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/janinge-stolek-barowy-szary__0873831_pe595574_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-11',
      name: 'Tommaryd 11',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/janinge-krzeslo-z-podlokietnikami-szary__0872870_pe595419_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-12',
      name: 'Tommaryd 12',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/yngvar-stolek-barowy-antracyt__0929674_ph170546_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-13',
      name: 'Tommaryd 13',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/stensele-stol-jasnoszary-jasnoszary__0871560_pe719789_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-14',
      name: 'Tommaryd 14',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/yngvar-krzeslo-czerwony__0750852_pe746842_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-15',
      name: 'Tommaryd 15',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/stensele-roenninge-stol-i-2-krzesla-jasnoszary-jasnoszary-brzoza__0871560_pe719789_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-16',
      name: 'Tommaryd 16',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/norraker-stolek-barowy-z-oparciem-brzoza__0873716_pe720507_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-17',
      name: 'Tommaryd 17',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/ikea-ps-2012-krzeslo-z-podlokietnikami-czarny__0209104_pe326299_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-18',
      name: 'Tommaryd 18',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/janinge-krzeslo-bialy__0872443_pe653411_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-19',
      name: 'Tommaryd 19',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/norraker-stol-barowy-czarny__0872216_pe640955_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-20',
      name: 'Tommaryd 20',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/stensele-stol-barowy-antracyt-antracyt__0872101_pe719776_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-21',
      name: 'Tommaryd 21',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/svenbertil-krzeslo-z-podlokietnikami-bialy-dietmar-chrom__0483272_pe620785_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-22',
      name: 'Tommaryd 22',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/leifarne-krzeslo-z-podlokietnikami-bialy-dietmar-czarny__0483257_pe620786_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-23',
      name: 'Tommaryd 23',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/stensele-stol-antracyt-antracyt__0773241_pe756242_s5.jpg?f=xxs',
    },
    {
      id: 'Tommaryd-24',
      name: 'Tommaryd 24',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      photoBackground:
        'https://www.ikea.com/pl/pl/images/products/leifarne-krzeslo-z-podlokietnikami-ciemnozolty-dietmar-chrom__0745145_pe743604_s5.jpg?f=xxs',
    },
  ],
  cart: {
    products: [],
  },
  config: {
    rwdMode: 'dektop',
  },
};

export default initialState;
